export const SCHEDULE_FETCHING = "SCHEDULE_FETCHING";
export const SCHEDULE_SET = "SCHEDULE_SET";
export const TOGGLE_FULL_CALENDAR = "TOGGLE_FULL_CALENDAR";
export const UPDATE_SLOT_FILTER = "UPDATE_SLOT_FILTER";
export const UPDATE_SELECTED_DATE = "UPDATE_SELECTED_DATE";
export const UPDATE_DISPLAY_MONTH = "UPDATE_DISPLAY_MONTH";
export const DOCTOR_DETAILS_FETCHING = "DOCTOR_DETAILS_FETCHING";
export const DOCTOR_DETAILS_SET = "DOCTOR_DETAILS_SET";

